export const eventReality = {
  id: null,
  name: "",
  description: "",
  startDate: new Date(),
  endDate: new Date(),
  location: "",
  eventType: "",
  outdoor: "Outdoor",
  media: null,
  thumbnail: null,
  capacity: 0,
  region: "",
  createdAt: new Date(),
  updatedAt: new Date(),
};
